trigger:
- main
- dev
- qa

pool:
  name: Neel Pipelines

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.16.x'
  displayName: 'Install Node.js'

- script: npm install -g @angular/cli@18.1.3
  displayName: 'Install angular 18.1.3'

- script: npm install
  displayName: 'install dependencies'

- script: npm run build --production
  displayName: 'build'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/shell'
    ArtifactName: 'drop'
    publishLocation: 'Container'

